### ISSUE TITLE
Could we get the output in the Vienna format?

### ISSUE THREAD

**Issue by Codezy99** [jaswindersingh2/SPOT-RNA#16]
Dear Jaswinder,

The output files of SPOT-RNA includes the .ct, .bpseq and .prob files. I was wondering if there is an option that would allow us to have the output in the Vienna format? Besides, I wondered whether there is a recommended length for the input RNA sequence to get the most reliable local structure prediction. Thank you : )

Best regards,
You

**Comment by jaswindersingh2** [comment]
Hi You,

I have updated the SPOT-RNA and now it can provide output in Vienna format. To get output in Vienna format, you need to set the motifs flag to True (`--motifs True`) because it is using bpRNA script to get Vienna format output.

I would recommend a maximum sequence length of 500 nucleotides to get the most reliable prediction from SPOT-RNA. For longer sequences, you can try [LinearFold](https://github.com/LinearFold/LinearFold) or [LinearPartition](https://github.com/LinearFold/LinearPartition) tools.

Jaswinder

**Comment by Codezy99** [comment]
Hi Jaswinder,

Thank you for the new version and kindly help. I will try it out. Have a nice Easter : )

Best regards,
You
