### ISSUE TITLE
how to generate vectorgraph?

### ISSUE THREAD

**Issue by tianxiahuihui** [jaswindersingh2/SPOT-RNA#4]
Dear Sir:

I get the png result by using the web server. I want to change the color of some bases, but I cannot do it by adobe illustrator. So I want to know how to use the software to generate vectorgraph or pdf file.

Thank you.

**Comment by jaswindersingh2** [comment]
Hi

My suggestion would be rather than editing the .png file, use VARNA (http://varna.lri.fr/) or forna (http://rna.tbi.univie.ac.at/forna/) RNA secondary structure plotting tools. Input to these tools can be dbn or ct format output generated by the SPOT-RNA webserver. You can change the color of any base-pair using these tools. We also use VARNA in the backend of the SPOT-RNA web server for plotting the predicted secondary structure.

Thank you

**Comment by tianxiahuihui** [comment]
Thank you.

I need some time to try the two software. I have another question. Could I use your software to compare two RNA sequence secondary structure ? Because I want to know whether the gRNA sequences could binding the DNA sequence, but I am not sure about this idea.
